### ISSUE TITLE
Move to SciML?

### ISSUE THREAD

**Issue by ranocha** [devmotion/SimpleUnPack.jl#6]
This package has quite a lot of dependents since it's used wildly in the SciML ecosystem and related packages. Would it make sense to move it to the SciML organization so that more people can maintain it?

**Comment by devmotion** [comment]
I'm happy to move it an organization but there's nothing SciML-specific in this package, so I don't see why it should be moved there. Also I experienced multiple times that packages in an organization are not necessarily better maintained.
